---
# Build heat stack
- include: playbooks/build-heat-stack.yml

# workaround: Force all nodes to the ".openstacklocal" domain
- include: playbooks/openstacklocal_domain.yml

# Install and configure LDAP server
- include: playbooks/ldap_server.yml

# Bootstrap and puppetize puppetmaster
- include: playbooks/puppetmaster.yml

# workarounds for liberty/freeze
- include: playbooks/puppet_environment_mods.yml

# workaround: Force domain again since puppetmaster puppetization touches /etc/hosts
- include: playbooks/openstacklocal_domain.yml

# Puppetize nodes
- include: playbooks/puppetize_backends.yml
- include: playbooks/puppetize_apis.yml

# Post puppetization mods
- hosts: api[0]
  become: yes
  become_user: root
  tasks:
    - name: Disable horizon to keystone SSL verification
      lineinfile:
        path: /etc/openstack-dashboard/local_settings
        regexp: '.*OPENSTACK_SSL_NO_VERIFY.*'
        line: 'OPENSTACK_SSL_NO_VERIFY = True'
    - name: Change horizon login backend to ldap
      shell: sed -i 's/native/ldap/' /etc/openstack-dashboard/local_settings
