---
admingroup: admin
adminremove_passwords: yes
adminusers:
  - name: rlaurika
    state: present
    uid: 854
    group: rlaurika
    groups: "{{admingroup}}"
    shell: "{{adminshell}}"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2PRSsmzVnxJYbDQG7xs2dHOkPqKSeD+Fa1RRokrzWvVaF36PiYRaHAs4hlS8O4uNKWKmnJ+3+TXP5r0eePdXvYWILx0DzBlm8BLBi3zJdzOyhg5NhjXZxA0f2l3AJMQrDgMqwqeaoi2Wxb6dc4JRSpWtGjgZS53H3hLmjeUr4RlgtxA7vdG++NNgls5PIYEHKNH/1/42dNjEje4z+49XcPIVMyLyvetSr343+IXhhz9xXIzfc0LnI7TVAd3odBI109582ksLpO4EugZHDgIW947ZgeCTjibWn23nBQ0OubhOBvjFANwEVLpBoQv4uQgYClUp98mTK5m8LdTXI3kqwQ=="
  - name: khappone
    state: present
    uid: 18870
    group: khappone
    groups: "{{admingroup}}"
    shell: "{{adminshell}}"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0rWS9J9BGswsUN4KrGpEy7i4tZvgD0bNpF+H599R9oa40L0/R/WfG9rRDb8JjUkdNdlxp5+87r1jJ618xMPx+12rJCJev8A9MTM87Cfa/D/iNUZWCwwD+zRgydJDQMbjXz9kCWlbH7UIlWKcMGjo1n9W0jECfNXqZdCc+fopsc0gSFJIT+QMFDdR1P7IR46AKmgyxE6QXUqkKWcn8soGbt3P/XPUFu6naNUgsMjKyX0Ba4CbH1Bo+ObjCcx+UDxL9XergSDEoVT6VIEbfzgnq5bsHlwvKSMGsMIZikPkF4xlKoOAkiF3T7T7DWJ96XP2RYqCFL5dcIBsoTb6rneO6Q=="
  - name: cthomas
    state: present
    uid: 4459
    group: cthomas
    groups: "{{admingroup}}"
    shell: "{{adminshell}}"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGPvudLahmqBId5lVgG0d8r/KnDk74Fa9hu7O+iu9ppUslMizYvQCPif2Xmh3ZMWW55zoAEqCoUChMLqyEJKzZgVWnrl19SvygpummOhps7Dw5FMWDcRl9oZ8HnbEbsNptz3GoVGRdU4cjowLOrlxF1F/tnFPTHtrJojrB0kGZ5+PeoKhJKt3Zi5Do0hVxvjhGuKBWl8NYNT8oKaU2tB7ljbdgcoOKTdwHrucOZ8g8P55aCqAR8X1z9FWjkdqmrcUaj/8QSxNOQK8pO5dIIENJ+3UShXhukLoYLOnG3sSP9yyy+OsqAuIBB3XelP48loLzhvUVU217HNk1p4MeQX77"
  - name: glynn
    state: present
    uid: 27130
    group: glynn
    groups: "{{admingroup}}"
    shell: "{{adminshell}}"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEA5uCu3GyjXJ9YJOxTKf1K6ATnCSVrA2VpH3EYPpPtqQhEeMQa3IiunLeabPBKZ0l036zIXNkrTU4eQbnqyXr0thuNEe8EyAHtPSxrXFYgcWg0PJe0WF0cwZaStKbhfgYhCNN9K1RlRcCvm7ENzL1gSASQUiP+ozQt+HNp993pAZRDOWfFkJMLebLTf0ZVyziFjXCwV2jJWVUVodf3tTT7gX8OqCZpjJjjQtEZVZ7987eQPrNmrCfFta44QOO1kULXcZtnkZtsttlJ7H4FYQK2cU1fMxKhUZH1l4KJi20/kWebckpKhdsB9ALCwwXD9KRgcBmL3/qkLupDVi5OpxSogD9IaJeAxF7+kTpBXxwJ48h888yPAWRneO5hWZdo7sy5CUA1QkAbVuxr5unBmZqM/gDjIJP169sAxiTxpWQGJH9IqGvnb2j5h2ETF6L3bWeX5uSgy96xLwKe1bb2IIoKspqv0JBwNqdoW7UWgm9Q7R96m/5tEwEQdHLy1CZQAd5xdyIlkhfLsk8o8ocCMIJHfG7lPRYj1oJL5XtZ8ooMOfyXFXLJCgs56pSQmlVVrBX/IW2d45QzQiEQC7xNjfIqN5CxOKyCmhrhP55BGOjLZY2Iy5kpUdR73pgsaVQ90MJ/en159FtSOY96Z1MB5LtyWgp4K/aGGOnvkNooQAUzs0s= glynn@csc.fi"
  - name: junousia
    state: present
    uid: 10000136
    group: junousia
    groups: "{{admingroup}}"
    shell: "{{adminshell}}"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDkwIW8zSsQ4Imo38dHUKuedr2ojnegnrrWAq1sqOEaqpzlQ8zXhe4hIfEp8yHBZnMlKv8WtG60GOcDx71W2KSOcZGUb3dFwmRCdAnZ+aS/vWZk5fTZUqRTJGOhaRg7gDztKVxOFg26ACEZKTiqGmT5v5oTPLGJKqENXhuAZ/NpG1caZeiCcz5ucPCubFZVHkpz5/D0W6CkL+GQUP7cuiFTnevangbkPQLv3YLvWc1nU1fELoYsp58c6Zah81zXONaHAkYRhiwGWsr9ke7k/pVzxyXyt3c0Rl1WuyYZ2EQLYuongA3dYmPH6cUC99zhIympbCKMBxHD5WUgZqc3IqZGliOKb2DC+q4/Xex7sEimsxv0t0mx4mODuBgQAXJaV1rLN9SgCCwgzW3+RCaxwG8kdbvUkqvOZ0wHAf49qiOOqBVM0z9yXzS3+xalDbaaxE9+vQeLY/4fJBy9kJCDGo2bpl6f4kaigeNHNPnMu3T477QMZ7XgjOSui11r7MGjl1WV++SX7mgxVLWlMfsuIypvPPTcdMBGlLn5+qznmvldUj9aobQ3bMCPHTmE0/hNzmRMPYlzpudw+O9bnG2QnjBeeBef4JCWWShtCxgMShCvb/sbq5iw03oVxnSQX2cJ24SyHNr8N3a2anW6zE6yScCnIzeHmWpYdpXCjNNtY8RLjQ=="
  - name: pkoskine
    state: present
    uid: 856
    group: pkoskine
    groups: "{{admingroup}}"
    shell: "{{adminshell}}"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSvxtM0lwEBbrKO4FSVooTii2v7y5UMDbkkDgqeaSYDbGlrjyXBQZuMnm1OZkjFXjmhrXaMWWyzY5Q1uGGoJLLTNwGjn1MCIW1r9/xbnJeyCr6/jLvnQaDoCbzHfW24KWtjrholxfVBZyFRydx7smjVI92skon2E5aBNVz7pZ6UPuQ4KU/M2gEZ7rvNsFHzw8bkMYCATfCGvFRAUiIR/AFsdmB5aD7U3RDHMtHG+dnoZnGR+c3oSLUYo1G9KVmg+k/7+ASukmj8Lyyt9l0QgrQL+usOo8RlylTDTVLknkEG4ko8XI95yFL3ZhSw5z4h1mz6YloefaviWATeIVB/9wn pkoskine@dragon.x.csc.fi"
  - name: okraemer
    state: present
    uid: 90005
    groups: "{{admingroup}}"
    shell: "{{adminshell}}"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwd5jJTr/v5tefRLxiKzdDyuFanzppz51GrcZlscKkT9y/+XGhBQMEr+QYV/MuKVDhWoe9tf42m32xVHpJtuD0Z+LvNbP/wF27BW3k38Nm+TRSfEabdsuxvsbufHxCyoE0XmnOMBGm6IDCB8tkZSpb5XqA4r9d8yh/XHYYykMAXkkOFHbAjXpR9z/WqGBMYb3ck+ABiD2l/Hp2MjUL9C96yxtgzMwp4re/AQpDiJ9BVtg4AWXg40hgGCcVNMOjw3OnGoUd2fdI25gD1jVH6T0VzlqNGwcTSk3m/nFMO9xOdxY4t1msszlYr7j0D/C3ZF13b0dFg4yXkFV/jERt2ipz okraemer@okraemer-air13"
