---
# for extraction to ansible inventory
ooo_network_name: "ooo-mgmt-net"
# for heat
heat_stack_name: "ooo-stack"
heat_environment_file: "../files/ooo-heat-params.yml"
# for both
vm_user_account: "cloud-user"
