heat_template_version: 2015-10-15

description: >
  Build machines for deployment of OpenStack.

parameters:
  api_server_count:
    type: number
    default: 2
  ssh_key_name:
    description: The name of the SSH key in OpenStack to add to hosts.
    type: string
  api_node_names:
    description: List of api node hostnames
    type: string
    default: ["api-node0", "api-node1", ]
  ooo_network:
    description: The network to use for the VMs.
    type: string
  hb_network_name:
    description: The network to use for heartbeats.
    type: string
  jumphost_allow_ssh_cidr:
    description: The CIDR where SSH is allowed to the jumphost from.
    type: string
  galera_node_flavor:
    description: The flavor to use for Galera nodes.
    type: string
  galera_node_image:
    description: The image to use for Galera nodes.
    type: string
  puppet_node_flavor:
    description: The flavor to use for Puppet nodes.
    type: string
  puppet_node_image:
    description: The image to use for Puppet nodes.
    type: string
  floating_ip_pool:
    type: string
    label: Floating IP pool
    description: The pool from which floating IPs should be reserved.
    default: 'public'
  ooo_subnet_cidr:
    type: string
    description: The CIDR of the internal network for the instances.
  hb_subnet_cidr:
    type: string
    description: The CIDR of the heartbeat network of API nodes.
  hb_subnet_name:
    type: string
    description: The name of the heartbeat subnet of API nodes.

resources:
  backend_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: ooo_backend_secgroup
      rules:
        - protocol: tcp
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 3306
          port_range_max: 3306
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 4444
          port_range_max: 4444
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 4567
          port_range_max: 4567
        - protocol: udp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 4567
          port_range_max: 4567
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 4568
          port_range_max: 4568
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 27017
          port_range_max: 27017

  puppet_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: ooo_puppet_secgroup
      rules:
        - protocol: tcp
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 8140
          port_range_max: 8140
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 8081
          port_range_max: 8081
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          remote_ip_prefix: { get_param: jumphost_allow_ssh_cidr }
          port_range_min: 22
          port_range_max: 22

  frontend_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: ooo_frontend_secgroup
      rules:
        - protocol: icmp
        - protocol: tcp
        - protocol: tcp
          remote_ip_prefix: { get_param: ooo_subnet_cidr }
          port_range_min: 22
          port_range_max: 22

  hb_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: hb_network_name }

  hb_subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: { get_param: hb_subnet_cidr }
#      enable_dhcp: False
      gateway_ip: null
      name: { get_param: hb_subnet_name }
      network: { get_resource: hb_network }

  api_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: api_server_count}
      resource_def:
        type: api-node.yaml
        properties:
          index: "%index%"
          api_node_names: { get_param: api_node_names }
          hb_network_name: { get_param: hb_network_name }
          ooo_frontend_secgroup: { get_resource: frontend_secgroup }

  galera_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server
        properties:
          name: galera-node%index%
          flavor: { get_param: galera_node_flavor }
          image: { get_param: galera_node_image }
          key_name: { get_param: ssh_key_name }
          security_groups:
            - { get_resource: backend_secgroup }
          networks:
            - network: { get_param: ooo_network }
          metadata: { 'ansible_group': 'galera' }

  puppet_node:
    type: OS::Nova::Server
    properties:
      name: puppetnode
      flavor: { get_param: puppet_node_flavor }
      image: { get_param: puppet_node_image }
      key_name: { get_param: ssh_key_name }
      security_groups:
        - { get_resource: puppet_secgroup }
      networks:
        - network: { get_param: ooo_network }
      metadata: { 'ansible_group': 'puppet' }

  jumphost_public_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: floating_ip_pool }

  jumphost_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: jumphost_public_ip }
      server_id: { get_resource: puppet_node }

outputs:
  api_nodes_group:
    value: { get_attr: [api_nodes, api_node_show] }
  galera_nodes_group:
    description: The group of Galera nodes
    value: { get_attr: [galera_nodes, show] }
  puppet_node:
    description: The puppet node
    value: { get_attr: [puppet_node, show] }
