---
- hosts: ldap
  become: true
  become_user: root
  pre_tasks:
    - shell: mkdir /etc/openldap/slapd.d;mkdir /etc/ldap;touch /etc/ldap/acl.conf
      ignore_errors: true
  roles:
    - role: ansible-role-openldap-server
      openldap_server_domain_name: acme.org
      openldap_server_rootpw: "{{ vault_openldap_server_rootpw }}"
      openldap_server_enable_ssl: false
      openldap_enable_user_creation: true
      openldap_server_users:
        testuser:
          password: testuser
          fullname: testuser
          givenname: testuser
          surname: testuser
          email: testuser@localhost
          shell: /usr/bin/bash
          phone: "555-JUGS"
      openldap_server_groups:
        testgroup:
          - testuser
