# workaround: Prevent dhcp on eth[012] touching DNS
- hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: Modify interface network-scripts
      blockinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
        create: yes
        state: present
        insertbefore: '^DEVICE'
        block: |
          DEVICE="{{ item }}"
          BOOTPROTO="dhcp"
          ONBOOT="yes"
          PEERDNS="no"
      with_items: "{{ ansible_interfaces | difference('lo') }}"

# workaround: change novalocal to openstacklocal
- hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - meta: clear_host_errors
    - name: Generate /etc/hosts file
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
    - name: Add resolv_conf to cloud-init modules
      blockinfile:
        dest: /etc/cloud/cloud.cfg
        create: no
        state: present
        insertafter: '^ - ssh'
        block: |1
          - resolv_conf
    - name: Add hostname and resolv config
      blockinfile:
        dest: /etc/cloud/cloud.cfg.d/99_hostname.cfg
        create: yes
        state: present
        block: |
          hostname: {{ inventory_hostname_short }}.openstacklocal
          manage-resolv-conf: true
          manage_resolv_conf: true
          resolv_conf:
            nameservers: {{ cloud_init_nameservers }}
            searchdomains:
              - openstacklocal
            domain: openstacklocal
            options:
              rotate: true
              timeout: 1
      notify:
        - Reboot
    - meta: flush_handlers
    - pause:
        seconds: 10
    - meta: clear_host_errors

  handlers:
    - name: Reboot
      shell: sleep 5 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true
