# workaround: change novalocal to openstacklocal
- hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: Activate ext interfaces
      shell: killall dhclient;dhclient eth1
      when: hostvars[inventory_hostname]['ansible_eth1'] is defined
      no_log: true
      ignore_errors: true
    - name: Activate ext interfaces
      shell: killall dhclient;dhclient eth2
      when: hostvars[inventory_hostname]['ansible_eth2'] is defined
      no_log: true
      ignore_errors: true
    - meta: clear_host_errors
    - name: Generate /etc/hosts file
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
    - name: Add hostname config
      lineinfile:
        dest: /etc/cloud/cloud.cfg.d/99_hostname.cfg
        create: yes
        state: present
        line: "hostname: {{ inventory_hostname_short }}.openstacklocal"
      notify:
        - Reboot
    - meta: flush_handlers
    - pause:
        seconds: 10
    - meta: clear_host_errors

  handlers:
    - name: Reboot
      shell: sleep 5 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true
