# workaround: Prevent dhcp on eth[012] touching DNS
- hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: Modify interface network-scripts
      copy:
        content: |
          DEVICE="{{ item }}"
          BOOTPROTO="dhcp"
          ONBOOT="yes"
          PEERDNS="no"
        dest: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
      with_items: "{{ ansible_interfaces | difference('lo') }}"
    - meta: clear_host_errors
# workaround: change novalocal to openstacklocal
    - name: Generate /etc/hosts file
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
    - name: Add resolv_conf to cloud-init modules
      blockinfile:
        dest: /etc/cloud/cloud.cfg
        create: no
        state: present
        insertafter: '^ - ssh$'
        block: |1
          - resolv_conf
      notify:
        - Reboot
    - meta: flush_handlers
    - pause:
        seconds: 10
    - meta: clear_host_errors

  handlers:
    - name: Reboot
      shell: sleep 5 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true
