## Workaround: change novalocal to openstacklocal
- hosts: all
  become: yes
  become_user: root
  tasks:
    - meta: clear_host_errors
    - name: Generate /etc/hosts file
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
    - name: Add hostname config
      lineinfile:
        dest: /etc/cloud/cloud.cfg.d/99_hostname.cfg
        create: yes
        state: present
        line: "hostname: {{ inventory_hostname_short }}.openstacklocal"
      notify:
        - Reboot
    - meta: flush_handlers
    - name: Wait a bit
      pause:
        seconds: 10
    - meta: clear_host_errors

  handlers:
    - name: Reboot
      shell: sleep 5 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true
