---
#modifications to liberty/freeze
- hosts: puppet
  become: true
  become_user: root
  tasks:
    - name: workaround - hosts file gets overwritten
      shell: sed -i '/hosts\.erb/d' /etc/puppet/environments/ooo/modules/cccp/manifests/role.pp
    - name: workaround - all galera nodes as master
      shell: sed -i 's/\${server_csl}//' /etc/puppet/environments/ooo/modules/galera/manifests/params.pp
    - name: fix changed repo url
      shell: sed -i 's/http:\/\/ceph.com/http:\/\/download.ceph.com/' /etc/puppet/environments/ooo/modules/ceph/manifests/yum/ceph.pp
    - name: workaround - vip for dhcp ip
      shell: sed -i 's/<\%\=\ @internal_vip\ \%>/{{ hostvars['api-node0']['ansible_eth0']['ipv4']['address'] }}/' /etc/puppet/environments/ooo/modules/cccp/templates/cib.txt.erb
      when: hostvars['api-node0']['ansible_eth0'] is defined
    - name: workaround - vip for dhcp ip
      shell: sed -i 's/<\%\=\ @external_vip\ \%>/{{ hostvars['api-node0']['ansible_eth1']['ipv4']['address'] }}/' /etc/puppet/environments/ooo/modules/cccp/templates/cib.txt.erb
      when: hostvars['api-node0']['ansible_eth1'] is defined
    #todo: netmask
    - name: workaround - disable pacemaker requirements
      shell: sed -i 's/\(^\s*require.*pacemaker\)/#\1/' /etc/puppet/environments/ooo/modules/cccp/manifests/profile/{{ item }}.pp
      with_items:
        - horizon
        - keystone
        - nova
        - neutron
        - glance
        - cinder
    - name: workaround - disable pacemaker requirements
      shell: sed -i 's/\(^\s*require.*pacemaker\)/#\1/' /etc/puppet/environments/ooo/modules/cccp/manifests/profile/ha/pacemaker/node_api.pp
    - name: workaround - disable crm
      shell: sed -i "s/.*unless.*/\ \ \ \ unless\ \ \=>\ '\/bin\/true',/" /etc/puppet/environments/ooo/modules/cccp/manifests/profile/ha/pacemaker/node_api.pp
    - name: workaround - disable pacemaker
      shell: sed -i 's/\(^\s*ensure.*running\)/#\1/' /etc/puppet/environments/ooo/modules/cccp/manifests/profile/ha/pacemaker/common.pp
    - name: workaround - remove reference to cs_primitive
      shell: sed -i '/pri_cinder_volume/,+13d' /etc/puppet/environments/ooo/modules/cccp/manifests/profile/cinder.pp
